// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kghvxcstzsoxqujamofg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtnaHZ4Y3N0enNveHF1amFtb2ZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MDc0NjAsImV4cCI6MjA2NjI4MzQ2MH0._xiqdacJMGUqkQYDa30DjrmY3ubGA_sLDSwNWTwLXgs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);